In [1]:
import torch

In [2]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.ones([3,4,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
x = torch.Tensor([[1,2],[3,4]])

In [6]:
x.size()

torch.Size([2, 2])

In [8]:
x.shape

torch.Size([2, 2])

In [9]:
x[0]

tensor([1., 2.])

In [11]:
x[1][0]

tensor(3.)

In [13]:
x[0][0:2]

tensor([1., 2.])

In [14]:
x[:,1]

tensor([2., 4.])

In [15]:
x+2

tensor([[3., 4.],
        [5., 6.]])

In [16]:
x ** 2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [17]:
y = torch.Tensor([[0,2],[5,6]])

In [18]:
x*y

tensor([[ 0.,  4.],
        [15., 24.]])

In [19]:
x % y

tensor([[nan, 0.],
        [3., 4.]])

In [20]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

In [21]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
a + b

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

In [23]:
a % b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
b[0]

tensor([1., 2., 3., 4.])

In [25]:
b[0] + a[2]

tensor([2., 3., 4., 5.])

In [26]:
a.dtype

torch.float32

In [27]:
import numpy as np

In [29]:
x = torch.from_numpy(np.array([1,2,3,4]))

In [30]:
x

tensor([1, 2, 3, 4])

In [31]:
x = torch.rand([2,3])

In [32]:
x

tensor([[0.7541, 0.4896, 0.4917],
        [0.8769, 0.6076, 0.5075]])

In [33]:
torch.cuda.is_available()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


False